import { exec } from 'child_process';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// --- State: AI background removal availability ---
export let isBgRemovalEnabled = true;
export let bgRemovalDisableReason = '';

/**
 * Resolve the Python executable path.
 * Priority: PYTHON_PATH env var > python3 (Linux/macOS) > python (Windows)
 */
const getPythonPath = () => {
  if (process.env.PYTHON_PATH) return process.env.PYTHON_PATH;
  return process.platform === 'win32' ? 'python' : 'python3';
};

/**
 * Verify Python and required packages are available on startup.
 * If verification fails, disables the feature gracefully without crashing the server.
 */
export const verifyPythonDependencies = () => {
  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const checkCmd = `${pythonPath} -c "from rembg import remove; from PIL import Image; print('OK')"`;

    exec(checkCmd, { timeout: 30000 }, (error, stdout, stderr) => {
      if (error || !stdout.includes('OK')) {
        isBgRemovalEnabled = false;
        const errDetail = stderr || error?.message || 'Unknown error';
        bgRemovalDisableReason = `Python dependency check failed: ${errDetail.trim()}`;
        console.warn(`[backgroundRemovalService] ⚠️  AI Background Removal DISABLED: ${bgRemovalDisableReason}`);
        console.warn(`[backgroundRemovalService] The Manual Eraser (client-side) will remain available.`);
      } else {
        isBgRemovalEnabled = true;
        bgRemovalDisableReason = '';
        console.log(`[backgroundRemovalService] ✅ AI Background Removal verified and ready (python: ${pythonPath})`);
      }
      resolve();
    });
  });
};

/**
 * Service to remove background from an image using local Python rembg.
 * @param {string} imageBase64 - The input image base64 string (can include data:image/*;base64, prefix)
 * @returns {Promise<string>} - Output transparent image as base64 string
 */
export const removeBackground = (imageBase64) => {
  return new Promise((resolve, reject) => {
    try {
      // 1. Prepare base64 data
      let base64Data = imageBase64;
      if (imageBase64.includes(';base64,')) {
        base64Data = imageBase64.split(';base64,')[1];
      }

      const buffer = Buffer.from(base64Data, 'base64');
      
      // 2. Generate unique temporary filenames
      const tempId = Date.now() + '_' + Math.round(Math.random() * 1000);
      const inputPath = path.join(__dirname, `temp_in_${tempId}.png`);
      const outputPath = path.join(__dirname, `temp_out_${tempId}.png`);

      // 3. Write input file
      fs.writeFileSync(inputPath, buffer);

      // 4. Resolve python script path
      const pythonScriptPath = path.join(__dirname, 'remove_bg.py');
      const pythonPath = getPythonPath();
      
      // 5. Execute python script
      const cmd = `${pythonPath} "${pythonScriptPath}" "${inputPath}" "${outputPath}"`;
      console.log(`[backgroundRemovalService] Executing: ${cmd}`);

      exec(cmd, { timeout: 120000 }, (error, stdout, stderr) => {
        // Clean up input file
        try {
          if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
        } catch (e) {
          console.warn("[backgroundRemovalService] Failed to delete input temp file:", e);
        }

        if (error) {
          const errMsg = stderr || stdout || error.message || "Python script failed";
          console.error(`[backgroundRemovalService] execution error: ${errMsg}`);
          // Clean up output file if exists
          try {
            if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
          } catch (e) {}
          return reject(new Error(errMsg));
        }

        console.log(`[backgroundRemovalService] stdout: ${stdout}`);
        
        try {
          if (!fs.existsSync(outputPath)) {
            return reject(new Error("Output file was not generated by background removal script"));
          }

          // 6. Read transparent output
          const outputBuffer = fs.readFileSync(outputPath);
          const outBase64 = outputBuffer.toString('base64');
          const dataUrl = `data:image/png;base64,${outBase64}`;

          // Clean up output file
          try {
            if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
          } catch (e) {}

          resolve(dataUrl);
        } catch (e) {
          reject(e);
        }
      });
    } catch (err) {
      reject(err);
    }
  });
};
