import { exec } from 'child_process';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Service to remove background from an image using local Python rembg.
 * @param {string} imageBase64 - The input image base64 string (can include data:image/*;base64, prefix)
 * @returns {Promise<string>} - Output transparent image as base64 string
 */
export const removeBackground = (imageBase64) => {
  return new Promise((resolve, reject) => {
    try {
      // 1. Prepare base64 data
      let base64Data = imageBase64;
      if (imageBase64.includes(';base64,')) {
        base64Data = imageBase64.split(';base64,')[1];
      }

      const buffer = Buffer.from(base64Data, 'base64');
      
      // 2. Generate unique temporary filenames
      const tempId = Date.now() + '_' + Math.round(Math.random() * 1000);
      const inputPath = path.join(__dirname, `temp_in_${tempId}.png`);
      const outputPath = path.join(__dirname, `temp_out_${tempId}.png`);

      // 3. Write input file
      fs.writeFileSync(inputPath, buffer);

      // 4. Resolve python script path
      const pythonScriptPath = path.join(__dirname, 'remove_bg.py');
      
      // 5. Execute python script
      const cmd = `python "${pythonScriptPath}" "${inputPath}" "${outputPath}"`;
      console.log(`[backgroundRemovalService] Executing: ${cmd}`);

      exec(cmd, { timeout: 60000 }, (error, stdout, stderr) => {
        // Clean up input file
        try {
          if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
        } catch (e) {
          console.warn("[backgroundRemovalService] Failed to delete input temp file:", e);
        }

        if (error) {
          console.error(`[backgroundRemovalService] execution error: ${stderr || error.message}`);
          // Clean up output file if exists
          try {
            if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
          } catch (e) {}
          return reject(new Error(stderr || error.message || "Python script failed"));
        }

        console.log(`[backgroundRemovalService] stdout: ${stdout}`);
        
        try {
          if (!fs.existsSync(outputPath)) {
            return reject(new Error("Output file was not generated by background removal script"));
          }

          // 6. Read transparent output
          const outputBuffer = fs.readFileSync(outputPath);
          const outBase64 = outputBuffer.toString('base64');
          const dataUrl = `data:image/png;base64,${outBase64}`;

          // Clean up output file
          try {
            if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
          } catch (e) {}

          resolve(dataUrl);
        } catch (e) {
          reject(e);
        }
      });
    } catch (err) {
      reject(err);
    }
  });
};
